# yaml 配置
version: "3.7"
#用于定义不同的应用服务
services:
  mysql8019:
    image: "mysql:8.0.19"
    ports:
      - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "blogs"
      MYSQL_PASSWORD: "123456"
    #volumes 用于指引 Docker 来创建新的卷
    volumes:
      - ./init.sql:/data/application/init.sql
  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"
  backbend:
    build: .
    command: sh -c "./wait-for.sh mysql8019:3306 redis507:6379 -- ./backbend ./conf/config.yaml"
    #设置依赖关系。
    depends_on:
      - mysql8019
      - redis507
    ports:
      - "8888:8082"