name: "bluebell"
mode: "dev"
port: 8082
version: "v0.0.1"
start_time: "2023-03-16"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "xiao_xiao_blog"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

check:
  file_path: "./file/sensitive-stop-words.txt"

elastic:
  url: "http://127.0.0.1:9200"
  index: "xiao_xiao_blog"